Repository adobe/aem-genai-assistant, pull requests merged in 2024-05, with the labels that each got.

#264 fix: Add execute permission to pre-app-deploy.js
  hooks/pre-app-deploy.js
Labels: Priority: High, Type: Bug, Status: Review Needed

#240 feat: add time groupings to recents list
  web-src/src/components/MainSidePanel.js
  web-src/src/helpers/FormatHelper.js
  web-src/src/helpers/FormatHelper.test.js
Labels: Ready to Deploy

#263 fix: Error handling for failure to load Express
  web-src/src/components/Constants.js
  web-src/src/components/FavoriteVariantCard.js
  web-src/src/components/PromptResultCard.js
  web-src/src/components/VariantImagesView.js
Labels: Status: Review Needed, Ready to Deploy

#252 feat: Implementation of early access feature flag toggle for Adobe internal users
  .github/workflows/deploy_prod.yml
  .github/workflows/deploy_qa.yml
  README.md
  actions/ActionUtils.js
  actions/ActionUtils.test.js
  actions/AuthAction.js
  app.config.yaml
  package-lock.json
  package.json
  web-src/src/components/AccessBoundary.js
  web-src/src/components/ApplicationProvider.js
  web-src/src/components/PromptResultCard.js
  web-src/src/components/ShellProvider.js
  web-src/src/index.js
  web-src/src/services/FirefallService.js
Labels: Status: Review Needed, Ready to Deploy

#251 docs: additional steps in README initial setup
  README.md
Labels: Ready to Deploy

#269 feat: Configure post-app-run hook to display the correct app url
  app.config.yaml
  hooks/post-app-run.js
Labels: Priority: Medium, Status: Review Needed, Ready to Deploy

#266 feat: reconcile settings before saving prompts
  web-src/src/components/ApplicationProvider.js
  web-src/src/components/GenerateButton.js
  web-src/src/components/MainSidePanel.js
  web-src/src/components/PromptResultCard.js
  web-src/src/components/PromptTemplatesView.js
  web-src/src/components/SavePromptButton.js
  web-src/src/state/PromptTemplatesState.js
  web-src/src/state/PromptTemplatesState.test.js
  web-src/src/state/RunMode.js
Labels: Priority: Critical

#261 Async calls
  README.md
  actions/AemClient.js
  actions/AuthAction.js
  actions/FirefallClient.js
  actions/GenericAction.js
  actions/Network.js
  actions/complete/index.js
  actions/generate/index.js
  app.config.yaml
  web-src/src/components/GenerateButton.js
  web-src/src/components/PromptSessionSideView.l10n.js
  web-src/src/components/__localization__/ContentFragmentExportButton.l10n/de_de.json
  web-src/src/components/__localization__/ContentFragmentExportButton.l10n/es_es.json
  web-src/src/components/__localization__/ContentFragmentExportButton.l10n/fr_fr.json
  web-src/src/components/__localization__/ContentFragmentExportButton.l10n/it_it.json
  web-src/src/components/__localization__/ContentFragmentExportButton.l10n/ja_jp.json
  web-src/src/components/__localization__/ContentFragmentExportButton.l10n/ko_kr.json
  web-src/src/components/__localization__/ContentFragmentExportButton.l10n/zh_cn.json
  web-src/src/components/__localization__/ContentFragmentExportButton.l10n/zh_tw.json
  web-src/src/components/__localization__/Favorites.l10n/de_de.json
  web-src/src/components/__localization__/Favorites.l10n/es_es.json
  web-src/src/components/__localization__/Favorites.l10n/fr_fr.json
  web-src/src/components/__localization__/Favorites.l10n/it_it.json
  web-src/src/components/__localization__/Favorites.l10n/ja_jp.json
  web-src/src/components/__localization__/Favorites.l10n/ko_kr.json
  web-src/src/components/__localization__/Favorites.l10n/pt_br.json
  web-src/src/components/__localization__/Favorites.l10n/zh_cn.json
  web-src/src/components/__localization__/Favorites.l10n/zh_tw.json
  web-src/src/components/__localization__/MainSidePanel.l10n/de_de.json
  web-src/src/components/__localization__/MainSidePanel.l10n/es_es.json
  web-src/src/components/__localization__/MainSidePanel.l10n/fr_fr.json
  web-src/src/components/__localization__/MainSidePanel.l10n/it_it.json
  web-src/src/components/__localization__/MainSidePanel.l10n/ja_jp.json
  web-src/src/components/__localization__/MainSidePanel.l10n/ko_kr.json
  web-src/src/components/__localization__/MainSidePanel.l10n/pt_br.json
  web-src/src/components/__localization__/MainSidePanel.l10n/zh_cn.json
  web-src/src/components/__localization__/MainSidePanel.l10n/zh_tw.json
  web-src/src/components/__localization__/PromptResultCard.l10n/es_es.json
  web-src/src/components/__localization__/PromptResultCard.l10n/fr_fr.json
  web-src/src/components/__localization__/PromptResultCard.l10n/it_it.json
  web-src/src/components/__localization__/PromptResultCard.l10n/ko_kr.json
  web-src/src/components/__localization__/PromptResultCard.l10n/pt_br.json
  web-src/src/components/__localization__/PromptResultCard.l10n/zh_cn.json
  web-src/src/components/__localization__/PromptResultCard.l10n/zh_tw.json
  web-src/src/components/__localization__/PromptSessionSideView.l10n/de_de.json
  web-src/src/components/__localization__/PromptSessionSideView.l10n/en_us.json
  web-src/src/components/__localization__/PromptSessionSideView.l10n/es_es.json
  web-src/src/components/__localization__/PromptSessionSideView.l10n/fr_fr.json
  web-src/src/components/__localization__/PromptSessionSideView.l10n/it_it.json
  web-src/src/components/__localization__/PromptSessionSideView.l10n/ja_jp.json
  web-src/src/components/__localization__/PromptSessionSideView.l10n/jl10n.json
  web-src/src/components/__localization__/PromptSessionSideView.l10n/ko_kr.json
  web-src/src/components/__localization__/PromptSessionSideView.l10n/pt_br.json
  web-src/src/components/__localization__/PromptSessionSideView.l10n/zh_cn.json
  web-src/src/components/__localization__/PromptSessionSideView.l10n/zh_tw.json
  web-src/src/helpers/ImageHelper.js
  web-src/src/helpers/NetworkHelper.js
  web-src/src/services/FirefallService.js
Labels: Priority: High
